// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMyIAjkWNEBgXERcns9GCgLFel5JX6sY',
    appId: '1:775250583572:web:26c7dace1e0bbe29b6c701',
    messagingSenderId: '775250583572',
    projectId: 'test-1-27571',
    authDomain: 'test-1-27571.firebaseapp.com',
    databaseURL: 'https://test-1-27571-default-rtdb.firebaseio.com',
    storageBucket: 'test-1-27571.appspot.com',
    measurementId: 'G-Q5QM7YZ97L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUpm4PSc7aA8hItUD9_Iy-SyqlyLPTjek',
    appId: '1:775250583572:android:fca8608722c71d08b6c701',
    messagingSenderId: '775250583572',
    projectId: 'test-1-27571',
    databaseURL: 'https://test-1-27571-default-rtdb.firebaseio.com',
    storageBucket: 'test-1-27571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcBJzBP4_qsnmB18BumImNAIA_l6ugN8M',
    appId: '1:775250583572:ios:79fbfe65af86f9d0b6c701',
    messagingSenderId: '775250583572',
    projectId: 'test-1-27571',
    databaseURL: 'https://test-1-27571-default-rtdb.firebaseio.com',
    storageBucket: 'test-1-27571.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcBJzBP4_qsnmB18BumImNAIA_l6ugN8M',
    appId: '1:775250583572:ios:b93cf2140a5896a7b6c701',
    messagingSenderId: '775250583572',
    projectId: 'test-1-27571',
    databaseURL: 'https://test-1-27571-default-rtdb.firebaseio.com',
    storageBucket: 'test-1-27571.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
